<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>tkom language</string>
    <key>scopeName</key>
    <string>source.tkom</string>
    <key>fileTypes</key>
    <array>
      <string>tkom</string>
      <string>conc</string>
    </array>
    <key>variables</key>
    <dict>
      <key>identifier</key>
      <string>[A-Za-z_]([a-zA-Z0-9]|_)*</string>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>(?&lt;=^)(fn)(?=\s)</string>
        <key>name</key>
        <string>function.keyword.tkom</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(\s*|^)(let)(?=\s)</string>
        <key>name</key>
        <string>variable.declaration.keyword.tkom</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\s*//.*</string>
        <key>name</key>
        <string>comment.line.tkom</string>
      </dict>
      <dict>
        <key>match</key>
        <string>(?&lt;=fn\s)([A-z][A-z0-9]*)(.*?)\s*\{</string>
        <key>name</key>
        <string>function.identifier.tkom</string>
      </dict>
      <dict>
        <key>match</key>
        <string>[A-Za-z_]([a-zA-Z0-9]|_)*</string>
        <key>name</key>
        <string>identifier.tkom</string>
      </dict>
      <dict>
        <key>match</key>
        <string>{{identifier}}</string>
        <key>name</key>
        <string>identifier.test.tkom</string>
      </dict>
    </array>
  </dict>
</plist>